var CONST;
var Config;
Config = {
    tv:1
}
//var KEY_ENUM = 100;
var KEY_ENUM = 400;
CONST = {

    BRAND_LIST: [
        "his", "wel", "nob", "jvc", "san", "phi", "ilo", "pio", "sma", "bgh", "blu",
        "dev", "kal", "cha", "pan", "tel", "riv", "con", "gen", "haa", "tit", "kmc", "vuz", "llo",
        "inn", "sho", "enf", "dlc", "hya", "dex", "sup", "oke", "rol", "sha", "har", "ezy", "ame",
        "dik", "cyb", "hyu", "gfo", "sei", "ton", "psc", "tho", "ora", "hisense", "Hisense", "off"
    ],

    RES_TYPE: {
        GROUP: 0,
        SPRITE: 1,
        SHAPE: 2,
        IMAGE: 3,
        HTML: 4,
        MULTIPLE: 5,
        TEXT: 6,
        PLACEHOLDER: 7,
        ANCHOR: 8,
        TEMPLATE: 9
    },

    SUB_TYPE: {
        INITIAL: 0,
        CALLED: 1,
        NORMAL: 2
    },

    LOAD_TYPE: {
        REMOVE: 0,
        HIDE: 1,
        BACKGROUND: 2
    },

    GIRD_DIRECTION: {
        H: 0,
        V: 1
    },

    NUMIPT_VALUE: {
        ZERO: 0,
        ONE: 1,
        TWO: 2,
        THREE: 3,
        FOUR: 4,
        FIVE: 5,
        SIX: 6,
        SEVEN: 7,
        EIGHT: 8,
        NINE: 9
    },

    LAUNCHER_MAXTILES : 20,

    KEY: {
        //VK_UNDEFINED : 0,
        VK_CANCEL : 3,
        VK_BACKSPACE : 8,
        VK_TAB : 9,
        VK_CLEAR : 12,
        VK_ENTER : 13,
        VK_SHIFT : 16,
        VK_CONTROL : 17,
        VK_ALT : 18,
        VK_PAUSE : 19,
        VK_CAPS_LOCK : 20,
        VK_KANA : 21,
        VK_FINAL : 24,
        VK_KANJI : 25,
        VK_ESCAPE : 27,
        VK_CONVERT : 28,
        VK_NONCONVERT : 29,
        VK_ACCEPT : 30,
        VK_MODECHANGE : 31,
        VK_SPACE : 32,
        VK_PAGE_UP : 33,
        VK_PAGE_DOWN : 34,
        VK_END : 35,
        VK_HOME : 36,
        VK_LEFT : 37,
        VK_UP : 38,
        VK_RIGHT : 39,
        VK_DOWN : 40,
        VK_COMMA : 44,
        VK_PERIOD : 46,
        VK_SLASH : 47,
        VK_0 : 48,
        VK_1 : 49,
        VK_2 : 50,
        VK_3 : 51,
        VK_4 : 52,
        VK_5 : 53,
        VK_6 : 54,
        VK_7 : 55,
        VK_8 : 56,
        VK_9 : 57,
        VK_SEMICOLON : 59,
        VK_EQUALS : 61,
        VK_A : 65,
        VK_B : 66,
        VK_C : 67,
        VK_D : 68,
        VK_E : 69,
        VK_F : 70,
        VK_G : 71,
        VK_H : 72,
        VK_I : 73,
        VK_J : 74,
        VK_K : 75,
        VK_L : 76,
        VK_M : 77,
        VK_N : 78,
        VK_O : 79,
        VK_P : 80,
        VK_Q : 81,
        VK_R : 82,
        VK_S : 83,
        VK_T : 84,
        VK_U : 85,
        VK_V : 86,
        VK_W : 87,
        VK_X : 88,
        VK_Y : 89,
        VK_Z : 90,
        VK_a : 97,
        VK_b : 98,
        VK_c : 99,
        VK_d : 100,
        VK_e : 101,
        VK_f : 102,
        VK_g : 103,
        VK_h : 104,
        VK_i : 105,
        VK_j : 106,
        VK_k : 107,
        VK_l : 108,
        VK_m : 109,
        VK_n : 110,
        VK_o : 111,
        VK_p : 112,
        VK_q : 113,
        VK_r : 114,
        VK_s : 115,
        VK_t : 116,
        VK_u : 117,
        VK_v : 118,
        VK_w : 119,
        VK_x : 120,
        VK_y : 121,
        VK_z : 122,
        VK_OPEN_BRACKET : 91,
        VK_BACK_SLASH : 92,
        VK_CLOSE_BRACKET : 93,
        VK_NUMPAD0 : 96,
        VK_NUMPAD1 : 97,
        VK_NUMPAD2 : 98,
        VK_NUMPAD3 : 99,
        VK_NUMPAD4 : 100,
        VK_NUMPAD5 : 101,
        VK_NUMPAD6 : 102,
        VK_NUMPAD7 : 103,
        VK_NUMPAD8 : 104,
        VK_NUMPAD9 : 105,
        VK_MULTIPLY : 106,
        VK_ADD : 107,
        VK_SEPARATER : 108,
        VK_SUBTRACT : 109,
        VK_DECIMAL : 110,
        VK_DIVIDE : 111,
        VK_F1 : 112,
        VK_F2 : 113,
        VK_F3 : 114,
        VK_F4 : 115,
        VK_F5 : 116,
        VK_F6 : 117,
        VK_F7 : 118,
        VK_F8 : 119,
        VK_F9 : 120,
        VK_F10 : 121,
        VK_F11 : 122,
        VK_F12 : 123,
        VK_DELETE : 127,
        VK_NUM_LOCK : 144,
        VK_SCROLL_LOCK : 145,
        VK_PRINTSCREEN : 154,
        VK_INSERT : 155,
        VK_HELP : 156,
        VK_META : 157,
        VK_BACK_QUOTE : 192,
        VK_QUOTE : 222,


        VK_EXCLAMATIONPOINT:33,
        VK_DOUBLEQUOTES:34,
        VK_HASHTAG:35,
        VK_DOLLAR:36,
        VK_PERCENT:37,
        VK_AMPERSAND:38,
        VK_SIGLEQUOTE:39,
        VK_OPENPARENTHESIS:40,
        VK_CLOSEPARENTHESIS:41,
        VK_ASTERISK:42,
        VK_PLUS:43,
        VK_HYPHEN:45,
        VK_COLON:58,
        VK_LESSTHAN:60,
        VK_GREATERTHAN:62,
        VK_QUESTIONMARK:63,
        VK_AT:64,
        VK_OPENBRACKET:91,
        VK_BACKSLASH:92,
        VK_CLOSEBRACKET:93,
        VK_CARET:94,
        VK_DASH:95,
        VK_OPENBRACE:123,
        VK_VERTICALBAR:124,
        VK_CLOSEBRACE:125,
        VK_TILDE:126,

        VK_LAUNCHER: KEY_ENUM++,
        VK_MENU: KEY_ENUM++,
        VK_VOLUME_UP: KEY_ENUM++,
        VK_VOLUME_DOWN: KEY_ENUM++,
        VK_KEYPAD_MENU:KEY_ENUM++,
        VK_ALLAPP: Config.tv ? KEY_ENUM++ : KEY_ENUM++,
        VK_KEYPAD_INPUT: Config.tv ? KEY_ENUM++ : KEY_ENUM++,
        VK_RED: KEY_ENUM++,
        VK_GREEN: KEY_ENUM++,
        VK_YELLOW: KEY_ENUM++,
        VK_BLUE: KEY_ENUM++,
        VK_FAC_M: KEY_ENUM++,
        VK_CHANNEL_UP: KEY_ENUM++,
        VK_CHANNEL_DOWN: KEY_ENUM++,
        VK_MUTE: KEY_ENUM++,
        VK_POWER: KEY_ENUM++,
        VK_PRE_CH: KEY_ENUM++,
        VK_INFO: KEY_ENUM++,
        VK_MEDIA: KEY_ENUM++,
        VK_CUSTOMER_3D: KEY_ENUM++,
        VK_PIP: KEY_ENUM++,
        VK_EPG: KEY_ENUM++,
        VK_LIVETV: KEY_ENUM++,
        VK_CH_LIST: KEY_ENUM++,
        VK_TOOLS: KEY_ENUM++,
        VK_PLAY: KEY_ENUM++,
        VK_STOP: KEY_ENUM++,
        VK_PVR: KEY_ENUM++,
        VK_LAST: KEY_ENUM++,
        VK_NEXT: KEY_ENUM++,
        VK_FAST_FWD: KEY_ENUM++,
        VK_FAST_BKW: KEY_ENUM++,
        VK_TELETEXT: KEY_ENUM++,
        VK_ZOOM: KEY_ENUM++,
        VK_T_SHIFT: KEY_ENUM++,
        VK_PICTURE: KEY_ENUM++,
        VK_S_MODE: KEY_ENUM++,
        VK_LANGUAGE: KEY_ENUM++,
        VK_SUBTITLE: KEY_ENUM++,
        VK_KEYPAD_CHANNEL_UP: KEY_ENUM++,
        VK_KEYPAD_CHANNEL_DOWN: KEY_ENUM++,
        VK_KEYPAD_VOLUME_UP: KEY_ENUM++,
        VK_KEYPAD_VOLUME_DOWN: KEY_ENUM++,
        VK_NETFLIX: KEY_ENUM++,
        VK_VUDU: KEY_ENUM++,
        VK_AMAZON: KEY_ENUM++,
        VK_YOUTUBE: KEY_ENUM++,
        VK_SHORT_LINE: KEY_ENUM++,
        VK_CC: KEY_ENUM++,
        VK_SOURCE: KEY_ENUM++,
        VK_SLEEP: KEY_ENUM++,
        VK_PICMODE_WIDE: KEY_ENUM++,
        VK_PICMODE_NORMAL: KEY_ENUM++,
        VK_PICMODE_CINEMA: KEY_ENUM++,
        VK_PICMODE_PANORAMA: KEY_ENUM++,
        VK_PICMODE_ZOOM: KEY_ENUM++,
        VK_SERVICE_TUNER1: KEY_ENUM++,
        VK_SERVICE_TUNER2: KEY_ENUM++,
        VK_AV1: KEY_ENUM++,
        VK_AV2: KEY_ENUM++,
        VK_AV3: KEY_ENUM++,
        VK_COMPONENT1: KEY_ENUM++,
        VK_COMPONENT2: KEY_ENUM++,
        VK_COMPONENT3: KEY_ENUM++,
        VK_HDMI1: KEY_ENUM++,
        VK_HDMI2: KEY_ENUM++,
        VK_HDMI3: KEY_ENUM++,
        VK_HDMI4: KEY_ENUM++,
        VK_HDMI5: KEY_ENUM++,
        VK_VGA: KEY_ENUM++,
        VK_ASPECT: KEY_ENUM++,
        VK_BT_CONNECT: KEY_ENUM++,
        VK_VOICE: KEY_ENUM++,
        VK_KPAD: KEY_ENUM++,
        VK_STICKER: KEY_ENUM++,
        VK_AUDIO_DESCRIPTION: KEY_ENUM++,
        VK_WUAKI: KEY_ENUM++,
        VK_LOWBATTERY: KEY_ENUM++,
        VK_POWER_ON: KEY_ENUM++,
        VK_POWER_KEY_PAD: KEY_ENUM++,
        VK_GREY : KEY_ENUM++,
        VK_BROWN : KEY_ENUM++,
        VK_DIMMER : KEY_ENUM++,
        VK_WINK : KEY_ENUM++,
        VK_REWIND : KEY_ENUM++,
        VK_EJECT_TOGGLE : KEY_ENUM++,
        VK_RECORD : KEY_ENUM++,
        VK_PLAY_SPEED_UP : KEY_ENUM++,
        VK_PLAY_SPEED_DOWN : KEY_ENUM++,
        VK_PLAY_SPEED_RESET : KEY_ENUM++,
        VK_RECORD_SPEED_NEXT : KEY_ENUM++,
        VK_GO_TO_START : KEY_ENUM++,
        VK_GO_TO_END : KEY_ENUM++,
        VK_TRACK_PREV : KEY_ENUM++,
        VK_TRACK_NEXT : KEY_ENUM++,
        VK_RANDOM_TOGGLE : KEY_ENUM++,
        VK_STORE_FAVORITE_0 : KEY_ENUM++,
        VK_STORE_FAVORITE_1 : KEY_ENUM++,
        VK_STORE_FAVORITE_2 : KEY_ENUM++,
        VK_STORE_FAVORITE_3 : KEY_ENUM++,
        VK_RECALL_FAVORITE_0 : KEY_ENUM++,
        VK_RECALL_FAVORITE_1 : KEY_ENUM++,
        VK_RECALL_FAVORITE_2 : KEY_ENUM++,
        VK_RECALL_FAVORITE_3 : KEY_ENUM++,
        VK_CLEAR_FAVORITE_0 : KEY_ENUM++,
        VK_CLEAR_FAVORITE_1 : KEY_ENUM++,
        VK_CLEAR_FAVORITE_2 : KEY_ENUM++,
        VK_CLEAR_FAVORITE_3 : KEY_ENUM++,
        VK_SCAN_CHANNELS_TOGGLE : KEY_ENUM++,
        VK_PINP_TOGGLE : KEY_ENUM++,
        VK_SPLIT_SCREEN_TOGGLE : KEY_ENUM++,
        VK_DISPLAY_SWAP : KEY_ENUM++,
        VK_SCREEN_MODE_NEXT : KEY_ENUM++,
        VK_VIDEO_MODE_NEXT : KEY_ENUM++,
        VK_SURROUND_MODE_NEXT : KEY_ENUM++,
        VK_BALANCE_RIGHT : KEY_ENUM++,
        VK_BALANCE_LEFT : KEY_ENUM++,
        VK_FADER_FRONT : KEY_ENUM++,
        VK_FADER_REAR : KEY_ENUM++,
        VK_BASS_BOOST_UP : KEY_ENUM++,
        VK_BASS_BOOST_DOWN : KEY_ENUM++,
        VK_GUIDE : KEY_ENUM++,
        VK_BACK : KEY_ENUM++,
        VK_EXIT : KEY_ENUM++,
        VK_STILL : KEY_ENUM++,
        VK_KB_Backspace : KEY_ENUM++,
        VK_KB_SQM : KEY_ENUM++,
        VK_KB_DQM : KEY_ENUM++,
        VK_KB_COMMA : KEY_ENUM++,
        VK_KB_DOT : KEY_ENUM++,
        VK_KB_SLASH : KEY_ENUM++,
        VK_KB_COLON : KEY_ENUM++,
        VK_KB_SEMICOLON : KEY_ENUM++,
        VK_KB_LT : KEY_ENUM++,
        VK_KB_GT : KEY_ENUM++,
        VK_KB_QUESTION : KEY_ENUM++,
        VK_KB_EM : KEY_ENUM++,
        VK_KB_AT : KEY_ENUM++,
        VK_KB_WELL : KEY_ENUM++,
        VK_KB_DOLLOR : KEY_ENUM++,
        VK_KB_PERSENT : KEY_ENUM++,
        VK_KB_JIAN : KEY_ENUM++,
        VK_KB_AND : KEY_ENUM++,
        VK_KB_STAR : KEY_ENUM++,
        VK_KB_LEFTBR : KEY_ENUM++,
        VK_KB_RIGHTBR : KEY_ENUM++,
        VK_KB_BIGLEFTBR : KEY_ENUM++,
        VK_KB_BIGRIGHTBR : KEY_ENUM++,
        VK_KB_LEFTBRACKET : KEY_ENUM++,
        VK_KB_RIGHTBRACKET : KEY_ENUM++,
        VK_KB_HOR : KEY_ENUM++,
        VK_KB_DASH : KEY_ENUM++,
        VK_KB_DUN : KEY_ENUM++,
        VK_KB_SUB : KEY_ENUM++,
        VK_KB_EQEAL : KEY_ENUM++,
        VK_KB_ADD : KEY_ENUM++,
        VK_KB_WAVE : KEY_ENUM++,
        VK_KB_RIGHTDASH : KEY_ENUM++,
        VK_KB_BlankString : KEY_ENUM++,
        VK_INPUT : KEY_ENUM++,
        VK_TEST : KEY_ENUM++,
        VK_VIRTUAL_HANDLE : KEY_ENUM++
    },
    KEYCODE_MAP: [],
    KEYVALUE_MAP: []
};

if (!Config.tv) {
    CONST.KEY.VK_LAUNCHER = CONST.KEY.VK_L;
    CONST.KEY.VK_MENU = CONST.KEY.VK_S;
    CONST.KEY.VK_TEST = CONST.KEY.VK_T;
    CONST.KEY.VK_SOURCE = CONST.KEY.VK_I;
    CONST.KEY.VK_ALLAPP = CONST.KEY.VK_A;
    CONST.KEY.VK_KEYPAD_MENU = CONST.KEY.VK_N;
}

// Keyboard
CONST.KEYBOARD_KEYCODE_MAP = [];
for (var id in CONST.KEY) {
    if (CONST.KEY.hasOwnProperty(id)) {
        CONST.KEYBOARD_KEYCODE_MAP[CONST.KEY[id]] = CONST.KEY[id];
    }
}

CONST.KEYBOARD_KEYCODE_MAP_SP = [];
CONST.KEYBOARD_KEYCODE_MAP_SP[103] = CONST.KEY.VK_UP;
CONST.KEYBOARD_KEYCODE_MAP_SP[108] = CONST.KEY.VK_DOWN;
CONST.KEYBOARD_KEYCODE_MAP_SP[105] = CONST.KEY.VK_LEFT;
CONST.KEYBOARD_KEYCODE_MAP_SP[106] = CONST.KEY.VK_RIGHT;

if (1) {
    // Remote
    CONST.KEYCODE_MAP[guijs.SYSCMD_ARROW_UP] = CONST.KEY.VK_UP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ARROW_DOWN] = CONST.KEY.VK_DOWN;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ARROW_LEFT] = CONST.KEY.VK_LEFT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ARROW_RIGHT] = CONST.KEY.VK_RIGHT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_OK] = CONST.KEY.VK_ENTER;
    CONST.KEYCODE_MAP[guijs.SYSCMD_0] = CONST.KEY.VK_0;
    CONST.KEYCODE_MAP[guijs.SYSCMD_1] = CONST.KEY.VK_1;
    CONST.KEYCODE_MAP[guijs.SYSCMD_2] = CONST.KEY.VK_2;
    CONST.KEYCODE_MAP[guijs.SYSCMD_3] = CONST.KEY.VK_3;
    CONST.KEYCODE_MAP[guijs.SYSCMD_4] = CONST.KEY.VK_4;
    CONST.KEYCODE_MAP[guijs.SYSCMD_5] = CONST.KEY.VK_5;
    CONST.KEYCODE_MAP[guijs.SYSCMD_6] = CONST.KEY.VK_6;
    CONST.KEYCODE_MAP[guijs.SYSCMD_7] = CONST.KEY.VK_7;
    CONST.KEYCODE_MAP[guijs.SYSCMD_8] = CONST.KEY.VK_8;
    CONST.KEYCODE_MAP[guijs.SYSCMD_9] = CONST.KEY.VK_9;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ONOFF] = CONST.KEY.VK_POWER;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PRE_CH] = CONST.KEY.VK_PRE_CH;
    CONST.KEYCODE_MAP[guijs.SYSCMD_INFO] = CONST.KEY.VK_INFO;
    CONST.KEYCODE_MAP[guijs.SYSCMD_VOLUME_UP] = CONST.KEY.VK_VOLUME_UP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_VOLUME_DOWN] = CONST.KEY.VK_VOLUME_DOWN;
    CONST.KEYCODE_MAP[guijs.SYSCMD_MUTE] = CONST.KEY.VK_MUTE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_CHANNEL_UP] = CONST.KEY.VK_CHANNEL_UP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_CHANNEL_DOWN] = CONST.KEY.VK_CHANNEL_DOWN;
    CONST.KEYCODE_MAP[guijs.SYSCMD_DMP] = CONST.KEY.VK_MEDIA;
    CONST.KEYCODE_MAP[guijs.SYSCMD_CUSTOMER_3D] = CONST.KEY.VK_CUSTOMER_3D;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PIP] = CONST.KEY.VK_PIP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_EPG] = CONST.KEY.VK_EPG;
    CONST.KEYCODE_MAP[guijs.SYSCMD_TV] = CONST.KEY.VK_LIVETV;
    CONST.KEYCODE_MAP[guijs.SYSCMD_CH_LIST] = CONST.KEY.VK_CH_LIST;
    CONST.KEYCODE_MAP[guijs.SYSCMD_MENU] = CONST.KEY.VK_MENU;
    CONST.KEYCODE_MAP[guijs.SYSCMD_SETTINGS] = CONST.KEY.VK_TOOLS;
    CONST.KEYCODE_MAP[guijs.SYSCMD_OK] = CONST.KEY.VK_ENTER;
    CONST.KEYCODE_MAP[guijs.SYSCMD_END] = CONST.KEY.VK_END;
    CONST.KEYCODE_MAP[guijs.SYSCMD_BACK] = CONST.KEY.VK_BACKSPACE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_EXIT] = CONST.KEY.VK_ESCAPE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ASSIST] = CONST.KEY.VK_LAUNCHER;
    CONST.KEYCODE_MAP[guijs.SYSCMD_HOME] = CONST.KEY.VK_LAUNCHER;
    CONST.KEYCODE_MAP[guijs.SYSCMD_RED] = CONST.KEY.VK_RED;
    CONST.KEYCODE_MAP[guijs.SYSCMD_GREEN] = CONST.KEY.VK_GREEN;
    CONST.KEYCODE_MAP[guijs.SYSCMD_YELLOW] = CONST.KEY.VK_YELLOW;
    CONST.KEYCODE_MAP[guijs.SYSCMD_BLUE] = CONST.KEY.VK_BLUE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_FAC_M] = CONST.KEY.VK_FAC_M;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PLAY] = CONST.KEY.VK_PLAY;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PAUSE] = CONST.KEY.VK_PAUSE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_STOP] = CONST.KEY.VK_STOP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_DMP_EXIT] = CONST.KEY.VK_STOP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PVR] = CONST.KEY.VK_PVR;
    CONST.KEYCODE_MAP[guijs.SYSCMD_LAST] = CONST.KEY.VK_LAST;
    CONST.KEYCODE_MAP[guijs.SYSCMD_NEXT] = CONST.KEY.VK_NEXT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_FAST_FWD] = CONST.KEY.VK_FAST_FWD;
    CONST.KEYCODE_MAP[guijs.SYSCMD_FAST_BKW] = CONST.KEY.VK_FAST_BKW;
    CONST.KEYCODE_MAP[guijs.SYSCMD_TEXT] = CONST.KEY.VK_TELETEXT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ZOOM] = CONST.KEY.VK_ZOOM;
    CONST.KEYCODE_MAP[guijs.SYSCMD_T_SHIFT] = CONST.KEY.VK_T_SHIFT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PICTURE] = CONST.KEY.VK_PICTURE;
    CONST.KEYCODE_MAP[guijs.SYSCMD__S_MODE] = CONST.KEY.VK_S_MODE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_SOUNDMENU] = CONST.KEY.VK_S_MODE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_LANGUAGE] = CONST.KEY.VK_LANGUAGE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_SUBTITLE] = CONST.KEY.VK_SUBTITLE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_FAC_F1] = CONST.KEY.VK_F1;
    CONST.KEYCODE_MAP[guijs.KEYPAD_CHANNEL_UP] = CONST.KEY.VK_KEYPAD_CHANNEL_UP;
    CONST.KEYCODE_MAP[guijs.KEYPAD_CHANNEL_DOWN] = CONST.KEY.VK_KEYPAD_CHANNEL_DOWN;
    CONST.KEYCODE_MAP[guijs.KEYPAD_VOLUME_UP] = CONST.KEY.VK_KEYPAD_VOLUME_UP;
    CONST.KEYCODE_MAP[guijs.KEYPAD_VOLUME_DOWN] = CONST.KEY.VK_KEYPAD_VOLUME_DOWN;
    CONST.KEYCODE_MAP[guijs.KEYPAD_INPUT] = CONST.KEY.VK_KEYPAD_INPUT;
    CONST.KEYCODE_MAP[guijs.KEYPAD_MENU] = CONST.KEY.VK_KEYPAD_MENU;
    CONST.KEYCODE_MAP[guijs.SYSPRG_ALLAPP] = CONST.KEY.VK_ALLAPP;
    CONST.KEYCODE_MAP[guijs.SYSPRG_NETFLIX] = CONST.KEY.VK_NETFLIX;
    CONST.KEYCODE_MAP[guijs.SYSPRG_VUDU] = CONST.KEY.VK_VUDU;
    CONST.KEYCODE_MAP[guijs.SYSPRG_AMAZON] = CONST.KEY.VK_AMAZON;
    CONST.KEYCODE_MAP[guijs.SYSPRG_YOUTUBE] = CONST.KEY.VK_YOUTUBE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_DIGIT_DOT] = CONST.KEY.VK_SHORT_LINE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_CC] = CONST.KEY.VK_CC;
    CONST.KEYCODE_MAP[guijs.SYSCMD_INPUT] = CONST.KEY.VK_SOURCE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_SLEEP] = CONST.KEY.VK_SLEEP;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PICMODE_WIDE] = CONST.KEY.VK_PICMODE_WIDE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PICMODE_NORMAL] = CONST.KEY.VK_PICMODE_NORMAL;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PICMODE_CINEMA] = CONST.KEY.VK_PICMODE_CINEMA;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PICMODE_PANORAMA] = CONST.KEY.VK_PICMODE_PANORAMA;
    CONST.KEYCODE_MAP[guijs.SYSCMD_PICMODE_ZOOM] = CONST.KEY.VK_PICMODE_ZOOM;
    CONST.KEYCODE_MAP[guijs.SYSCMD_SERVICE_TUNER1] = CONST.KEY.VK_SERVICE_TUNER1;
    CONST.KEYCODE_MAP[guijs.SYSCMD_SERVICE_TUNER2] = CONST.KEY.VK_SERVICE_TUNER2;
    CONST.KEYCODE_MAP[guijs.SYSCMD_AV1] = CONST.KEY.VK_AV1;
    CONST.KEYCODE_MAP[guijs.SYSCMD_AV2] = CONST.KEY.VK_AV2;
    CONST.KEYCODE_MAP[guijs.SYSCMD_AV3] = CONST.KEY.VK_AV3;
    CONST.KEYCODE_MAP[guijs.SYSCMD_COMP1] = CONST.KEY.VK_COMPONENT1;
    CONST.KEYCODE_MAP[guijs.SYSCMD_COMP2] = CONST.KEY.VK_COMPONENT2;
    CONST.KEYCODE_MAP[guijs.SYSCMD_COMP3] = CONST.KEY.VK_COMPONENT3;
    CONST.KEYCODE_MAP[guijs.SYSCMD_HDMI1] = CONST.KEY.VK_HDMI1;
    CONST.KEYCODE_MAP[guijs.SYSCMD_HDMI2] = CONST.KEY.VK_HDMI2;
    CONST.KEYCODE_MAP[guijs.SYSCMD_HDMI3] = CONST.KEY.VK_HDMI3;
    CONST.KEYCODE_MAP[guijs.SYSCMD_HDMI4] = CONST.KEY.VK_HDMI4;
    CONST.KEYCODE_MAP[guijs.SYSCMD_HDMI5] = CONST.KEY.VK_HDMI5;
    CONST.KEYCODE_MAP[guijs.SYSCMD_VGA] = CONST.KEY.VK_VGA;
    CONST.KEYCODE_MAP[guijs.SYSCMD_ASPECT] = CONST.KEY.VK_ASPECT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_BT_CONNECT] = CONST.KEY.VK_BT_CONNECT;
    CONST.KEYCODE_MAP[guijs.SYSCMD_VOICE] = CONST.KEY.VK_VOICE;
    CONST.KEYCODE_MAP[guijs.SYSCMD_KEYPADE] = CONST.KEY.VK_KPAD;
    CONST.KEYCODE_MAP[guijs.SYSCMD_STICKER] = CONST.KEY.VK_STICKER;
    CONST.KEYCODE_MAP[guijs.SYSCMD_AUDIO_DESCRIPTION] = CONST.KEY.VK_AUDIO_DESCRIPTION;
    CONST.KEYCODE_MAP[guijs.SYSCMD_WUAKI] = CONST.KEY.VK_WUAKI;
    CONST.KEYCODE_MAP[guijs.SYSCMD_LOW_BATTERY] = CONST.KEY.VK_LOWBATTERY;
    CONST.KEYCODE_MAP[guijs.SYSCMD_POWER_ON] = CONST.KEY.VK_POWER_ON;
    CONST.KEYCODE_MAP[guijs.SYSCMD_POWERKEYPAD] = CONST.KEY.VK_POWER_KEY_PAD;
    CONST.KEYCODE_MAP[guijs.SYSCMD_POWER] = CONST.KEY.VK_POWER;

    CONST.KEYCODE_MAP[guijs.SYSCMD_VIRTUAL_HANDLE] = CONST.KEY.VK_VIRTUAL_HANDLE;
}

{
    CONST.KEYVALUE_MAP[CONST.KEY.VK_UP] = "UP";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_DOWN] = "DOWN";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_LEFT] = "LEFT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_RIGHT] = "RIGHT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_ENTER] = "ENTER";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_BACKSPACE] = "BACKSPACE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_ESCAPE] = "ESCAPE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_0] = "ZERO";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_1] = "ONE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_2] = "TWO";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_3] = "THREE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_4] = "FOUR";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_5] = "FIVE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_6] = "SIX";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_7] = "SEVEN";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_8] = "EIGHT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_9] = "NINE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_LAUNCHER] = "LAUNCHER";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KEYPAD_MENU] = "KEYPADMENU";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_MENU] = "MENU";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_VOLUME_UP] = "VALPLUS";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_VOLUME_DOWN] = "VALMINUS";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_MUTE] = "MUTE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KEYPAD_CHANNEL_UP] = "CHUP";// Please notify bob before you modify this value, THX.
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KEYPAD_CHANNEL_DOWN] = "CHDOWN";// Please notify bob before you modify this value, THX.
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KEYPAD_VOLUME_UP] = "VALPLUS";// Please notify bob before you modify this value, THX.
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KEYPAD_VOLUME_DOWN] = "VALMINUS";// Please notify bob before you modify this value, THX.
    CONST.KEYVALUE_MAP[CONST.KEY.VK_CHANNEL_UP] = "CHUP";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_CHANNEL_DOWN] = "CHDOWN";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_RED] = "RED";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_GREEN] = "GREEN";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_YELLOW] = "YELLOW";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_BLUE] = "BLUE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_FAC_M] = "FACM";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PRE_CH] = "PRE_CH";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_INFO] = "INFO";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_MEDIA] = "MEDIA";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_CUSTOMER_3D] = "CUSTOMER_3D";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PIP] = "PIP";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_EPG] = "EPG";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_LIVETV] = "LIVETV";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_CH_LIST] = "CH_LIST";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_TOOLS] = "TOOLS";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_END] = "END";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PLAY] = "PLAY";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PAUSE] = "PAUSE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_STOP] = "STOP";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PVR] = "PVR";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_LAST] = "LAST";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_NEXT] = "NEXT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_FAST_FWD] = "FAST_FWD";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_FAST_BKW] = "FAST_BKW";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_TELETEXT] = "TELETEXT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_ZOOM] = "ZOOM";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_T_SHIFT] = "T_SHIFT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PICTURE] = "PICTURE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_S_MODE] = "S_MODE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_LANGUAGE] = "LANGUAGE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_SUBTITLE] = "SUBTITLE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_F1] = "F1";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_ALLAPP] = "ALLAPP";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_NETFLIX] = "NETFLIX";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_VUDU] = "VUDU";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_AMAZON] = "AMAZON";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_YOUTUBE] = "YOUTUBE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_SHORT_LINE] = "SHORT_LINE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_CC] = "CC";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_SOURCE] = "INPUT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KEYPAD_INPUT] = "INPUT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_SLEEP] = "SLEEP";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PICMODE_WIDE] = "PICMODE_WIDE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PICMODE_NORMAL] = "PICMODE_NORMAL";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PICMODE_CINEMA] = "PICMODE_CINEMA";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PICMODE_PANORAMA] = "PICMODE_PANORAMA";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_PICMODE_ZOOM] = "PICMODE_ZOOM";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_SERVICE_TUNER1] = "SERVICE_TUNER1";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_SERVICE_TUNER2] = "SERVICE_TUNER2";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_AV1] = "AV1";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_AV2] = "AV2";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_AV3] = "AV3";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_COMPONENT1] = "COMPONENT1";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_COMPONENT2] = "COMPONENT2";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_COMPONENT3] = "COMPONENT3";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_HDMI1] = "HDMI1";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_HDMI2] = "HDMI2";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_HDMI3] = "HDMI3";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_HDMI4] = "HDMI4";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_HDMI5] = "HDMI5";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_VGA] = "VGA";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_ASPECT] = "ASPECT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_BT_CONNECT] = "BT_CONNECT";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_VOICE] = "VOICE";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_KPAD] = "KPAD";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_STICKER] = "STICKER";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_AUDIO_DESCRIPTION] = "AUDIO_DESCRIPTION";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_WUAKI] = "WUAKI";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_LOWBATTERY] = "LOWBATTERY";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_POWER_ON] = "POWER_ON";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_POWER_KEY_PAD] = "POWER_ON";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_POWER] = "POWER";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_TEST] = "TEST";
    CONST.KEYVALUE_MAP[CONST.KEY.VK_VIRTUAL_HANDLE] = "VIRTUALHANDLE";
}

// Keyboard
CONST.KEYBOARD_KEYVALUE_MAP = [];
for (var id in CONST.KEY) {
    if (CONST.KEY.hasOwnProperty(id)) {
        CONST.KEYBOARD_KEYVALUE_MAP[CONST.KEY[id]] = id.replace("VK_", "");
    }
}

CONST.KEYBOARD_KEYVALUE_MAP_SP = [];
CONST.KEYBOARD_KEYVALUE_MAP_SP[103] = "UP";
CONST.KEYBOARD_KEYVALUE_MAP_SP[108] = "DOWN";
CONST.KEYBOARD_KEYVALUE_MAP_SP[105] = "LEFT";
CONST.KEYBOARD_KEYVALUE_MAP_SP[106] = "RIGHT";

CONST.KEY_STATE = {
    DOWN: 1,
    REPEAT: 2,
    UP: 8
};

CONST.CEC_KEYSET = [
    CONST.KEY.VK_UP, CONST.KEY.VK_DOWN, CONST.KEY.VK_LEFT,
    CONST.KEY.VK_RIGHT, CONST.KEY.VK_ENTER, CONST.KEY.VK_PLAY,
    CONST.KEY.VK_STOP, CONST.KEY.VK_BACKSPACE, CONST.KEY.VK_PAUSE,
    CONST.KEY.VK_FAST_BKW, CONST.KEY.VK_FAST_FWD
];

CONST.CEC_KEYMAP = {};
CONST.CEC_ENUM = 0x41;

CONST.CEC_KEYMAP[CONST.KEY.VK_VOLUME_UP] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_VOLUME_DOWN] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_MUTE] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_PLAY] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_STOP] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_PAUSE] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_FAST_FWD] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_FAST_BKW] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_LEFT] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_UP] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_RIGHT] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_DOWN] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_ENTER] = CONST.CEC_ENUM++;
CONST.CEC_KEYMAP[CONST.KEY.VK_BACKSPACE] = CONST.CEC_ENUM++;

CONST.TELETEXT_KEYSET = [
    CONST.KEY.VK_UP, CONST.KEY.VK_DOWN, CONST.KEY.VK_LEFT,
    CONST.KEY.VK_RIGHT, CONST.KEY.VK_ENTER, CONST.KEY.VK_PLAY,
    CONST.KEY.VK_STOP, CONST.KEY.VK_PAUSE, CONST.KEY.VK_FAST_BKW,
    CONST.KEY.VK_FAST_FWD, CONST.KEY.VK_0, CONST.KEY.VK_1,
    CONST.KEY.VK_2, CONST.KEY.VK_3, CONST.KEY.VK_4, CONST.KEY.VK_5,
    CONST.KEY.VK_6, CONST.KEY.VK_7, CONST.KEY.VK_8, CONST.KEY.VK_9,
    CONST.KEY.VK_RED, CONST.KEY.VK_GREEN, CONST.KEY.VK_YELLOW,
    CONST.KEY.VK_BLUE, CONST.KEY.VK_TELETEXT, CONST.KEY.VK_ESCAPE,
    CONST.KEY.VK_CHANNEL_DOWN, CONST.KEY.VK_CHANNEL_UP]
;

CONST.HBBTV_COUNTRY = ["AUS"];
CONST.HBBTV_COEXIST = ["netflix"];

CONST.SHORT_MONTH = ['[SE1343]', '[TV0041]', '[TV0042]', '[TV0043]', '[TV0044]', '[TV0045]', '[TV0046]', '[TV0047]', '[TV0048]', '[TV0049]', '[TV0050]', '[TV0051]'];
CONST.SHORT_WEEK = ['[SE1321]', '[SE1322]', '[SE1323]', '[SE1324]', '[SE1325]', '[SE1326]', '[SE1327]'];
CONST.LONG_WEEK = ["[GE0027]","[GE0021]","[GE0022]","[GE0023]","[GE0024]","[GE0025]","[GE0026]"];

CONST.ATV = 1;
CONST.DTV = 2;  //DTV�?3?

CONST.USERTILE = [
    "#cf3c60",
    "#b03268",
    "#982c80",
    "#7d2b71",
    "#5a2967",
    "#3c2e70",
    "#333788",
    "#2a4a8f",
    "#305d97",
    "#2f74a3",
    "#357f97",
    "#369098",
    "#3ca69d",
    "#58b199",
    "#31987e"
];

CONST.BLUETOOTH_KEYMAP = {}
CONST.BLUETOOTH_ENUM = 0;

CONST.BLUETOOTH_KEYMAP[CONST.KEY.VK_VOLUME_UP] = CONST.BLUETOOTH_ENUM++;
CONST.BLUETOOTH_KEYMAP[CONST.KEY.VK_VOLUME_DOWN] = CONST.BLUETOOTH_ENUM++;
CONST.BLUETOOTH_KEYMAP[CONST.KEY.VK_MUTE] = CONST.BLUETOOTH_ENUM++;